default_platform(:android)

platform :android do
    lane :increment_build do
        increment_version_code(
            gradle_file_path: "Wearable/build.gradle",
        )
    end

    desc "Build the Wear OS app"
    lane :build do
        increment_build
        gradle(task: ":Wearable:bundleRelease")
    end

    desc "Deploy to Google Play Store (internal track)"
    lane :deploy do
        build
        supply(
          track: "internal",
          aab: "Wearable/build/outputs/bundle/release/Wearable-release.aab",
          skip_upload_metadata: true,
          skip_upload_images: true,
          skip_upload_screenshots: true,
          skip_upload_apk: true
        )
    end
end
