default_platform(:android)

platform :android do
    desc "Build the Wear OS app"
    lane :build do
        gradle(task: ":app:bundleRelease")
    end

    desc "Deploy to Google Play Store (internal track)"
    lane :deploy do
        build
        supply(
          track: "internal",
          aab: "app/build/outputs/bundle/release/app-release.aab",
          skip_upload_metadata: true,
          skip_upload_images: true,
          skip_upload_screenshots: true,
          skip_upload_apk: true
        )
    end
end
